In [12]:
import pandas as pd
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

In [13]:
liga_pre = pd.read_csv('LIGA05-19_wValues.csv')

In [14]:
liga_pre.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5289 entries, 0 to 5288
Data columns (total 22 columns):
Date         5289 non-null object
HomeTeam     5289 non-null object
HomeValue    5289 non-null int64
AwayTeam     5289 non-null object
AwayValue    5289 non-null int64
B365H        5289 non-null float64
B365D        5289 non-null float64
B365A        5289 non-null float64
BWH          5289 non-null float64
BWD          5289 non-null float64
BWA          5289 non-null float64
IWH          5289 non-null float64
IWD          5289 non-null float64
IWA          5289 non-null float64
VCH          5289 non-null float64
VCD          5289 non-null float64
VCA          5289 non-null float64
WHH          5289 non-null float64
WHD          5289 non-null float64
WHA          5289 non-null float64
HTR          5289 non-null object
FTR          5289 non-null object
dtypes: float64(15), int64(2), object(5)
memory usage: 909.2+ KB

In [15]:
#liga_pre.drop(['Unnamed: 0'], axis = 1, inplace = True)
liga_pre['Date'] = liga_pre['Date'].astype('datetime64[ns]')

In [16]:
liga_pre.head()
liga_pre.drop(['Date'], axis=1, inplace=True) #dropping DATE at early ML.

In [17]:
liga_pre.drop(['HTR'], axis=1, inplace=True) #dropping result at Half Time

In [18]:
liga_pre.dtypes

HomeTeam      object
HomeValue      int64
AwayTeam      object
AwayValue      int64
B365H        float64
B365D        float64
B365A        float64
BWH          float64
BWD          float64
BWA          float64
IWH          float64
IWD          float64
IWA          float64
VCH          float64
VCD          float64
VCA          float64
WHH          float64
WHD          float64
WHA          float64
FTR           object
dtype: object

In [20]:
to_encode = liga_pre.select_dtypes(include=[object])
to_encode.head()

     HomeTeam     AwayTeam FTR
0      Alaves    Barcelona   D
1    Valencia        Betis   H
2  Ath Madrid     Zaragoza   D
3       Cadiz  Real Madrid   A
4       Celta       Malaga   H

In [21]:
# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()


# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
features_encoded = to_encode.apply(le.fit_transform)
features_encoded.head(10)

   HomeTeam  AwayTeam  FTR
0         0         4    1
1        34         5    2
2         3        39    1
3         6        27    0
4         7        22    2
5        11        12    0
6        23        18    0
7        26        37    2
8        30        29    2
9         5        26    2

In [22]:
liga_pre.drop(['HomeTeam', 'AwayTeam', 'FTR'], axis = 1, inplace = True)

In [23]:
liga_pre.head()

,HomeValue,AwayValue,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,VCH,VCD,VCA,WHH,WHD,WHA
0,20950000,275230000,7.00,3.75,1.50,7.00,3.70,1.45,5.4,3.5,1.5,6.50,3.75,1.45,6.00,3.4,1.50
1,21090000,78100000,2.00,3.25,3.25,1.75,3.30,4.40,1.9,3.0,3.6,1.85,3.25,3.75,1.95,3.1,3.50
2,113700000,52750000,1.72,3.40,4.00,1.65,3.40,4.90,1.7,3.1,4.4,1.65,3.40,4.50,1.70,3.2,4.50
3,1650000,283750000,7.50,4.00,1.44,8.00,4.25,1.35,5.4,3.5,1.5,6.50,3.60,1.45,6.50,3.6,1.44
4,36350000,21100000,2.10,3.25,3.00,2.10,3.10,3.30,2.1,2.9,3.2,2.00,3.20,3.25,2.15,3.1,3.00

In [24]:
features_encoded.head()

   HomeTeam  AwayTeam  FTR
0         0         4    1
1        34         5    2
2         3        39    1
3         6        27    0
4         7        22    2

In [26]:
result = pd.concat([liga_pre.stack(), features_encoded.stack()], axis=0).unstack()
result.head()

,AwayTeam,AwayValue,B365A,B365D,B365H,BWA,BWD,BWH,FTR,HomeTeam,HomeValue,IWA,IWD,IWH,VCA,VCD,VCH,WHA,WHD,WHH
0,4.0,275230000.0,1.50,3.75,7.00,1.45,3.70,7.00,1.0,0.0,20950000.0,1.5,3.5,5.4,1.45,3.75,6.50,1.50,3.4,6.00
1,5.0,78100000.0,3.25,3.25,2.00,4.40,3.30,1.75,2.0,34.0,21090000.0,3.6,3.0,1.9,3.75,3.25,1.85,3.50,3.1,1.95
2,39.0,52750000.0,4.00,3.40,1.72,4.90,3.40,1.65,1.0,3.0,113700000.0,4.4,3.1,1.7,4.50,3.40,1.65,4.50,3.2,1.70
3,27.0,283750000.0,1.44,4.00,7.50,1.35,4.25,8.00,0.0,6.0,1650000.0,1.5,3.5,5.4,1.45,3.60,6.50,1.44,3.6,6.50
4,22.0,21100000.0,3.00,3.25,2.10,3.30,3.10,2.10,2.0,7.0,36350000.0,3.2,2.9,2.1,3.25,3.20,2.00,3.00,3.1,2.15

In [27]:
cols = result.columns.tolist()
cols

['AwayTeam',
 'AwayValue',
 'B365A',
 'B365D',
 'B365H',
 'BWA',
 'BWD',
 'BWH',
 'FTR',
 'HomeTeam',
 'HomeValue',
 'IWA',
 'IWD',
 'IWH',
 'VCA',
 'VCD',
 'VCH',
 'WHA',
 'WHD',
 'WHH']

In [28]:
df = result [['AwayTeam', 'AwayValue', 'HomeTeam', 'HomeValue', 'B365A', 'B365D', 'B365H', 'BWA',
                  'BWD', 'BWH','IWA', 'IWD', 'IWH', 'VCA', 'VCD', 'VCH', 'WHA', 'WHD', 'WHH', 'FTR']]

In [29]:
df.transpose()

,0,1,2,3,4,5,6,7,8,9,...,5279,5280,5281,5282,5283,5284,5285,5286,5287,5288
AwayTeam,4.000000e+00,5.00,3.900000e+01,2.700000e+01,22.00,12.00,1.800000e+01,37.00,29.00,26.00,...,9.000000e+00,21.00,1.500000e+01,0.000000e+00,3.700000e+01,1.100000e+01,2.000000e+00,3.000000e+00,1.200000e+01,3.000000e+01
AwayValue,2.752300e+08,78100000.00,5.275000e+07,2.837500e+08,21100000.00,15950000.00,1.187000e+08,70000000.00,22850000.00,24000000.00,...,6.960000e+07,72500000.00,3.350000e+07,9.020000e+07,2.117000e+08,1.503000e+08,2.250000e+08,8.725000e+08,6.950000e+07,2.832000e+08
HomeTeam,0.000000e+00,34.00,3.000000e+00,6.000000e+00,7.00,11.00,2.300000e+01,26.00,30.00,5.00,...,5.000000e+00,20.00,2.700000e+01,3.400000e+01,2.600000e+01,2.300000e+01,7.000000e+00,3.500000e+01,3.100000e+01,4.000000e+00
HomeValue,2.095000e+07,21090000.00,1.137000e+08,1.650000e+06,36350000.00,55500000.00,3.990000e+07,24000000.00,73250000.00,78100000.00,...,1.803300e+08,92280000.00,1.090000e+09,4.955000e+08,4.350000e+07,5.855000e+07,1.817000e+08,9.280000e+07,3.098000e+08,1.160000e+09
B365A,1.500000e+00,3.25,4.000000e+00,1.440000e+00,3.00,5.00,2.300000e+00,2.30,4.50,4.50,...,3.700000e+00,3.80,1.000000e+01,6.500000e+00,2.400000e+00,3.000000e+00,2.870000e+00,1.720000e+00,4.330000e+00,7.000000e+00
B365D,3.750000e+00,3.25,3.400000e+00,4.000000e+00,3.25,3.40,3.200000e+00,3.20,3.40,3.40,...,3.600000e+00,3.50,5.750000e+00,4.330000e+00,3.300000e+00,3.250000e+00,3.000000e+00,3.500000e+00,3.400000e+00,4.200000e+00
B365H,7.000000e+00,2.00,1.720000e+00,7.500000e+00,2.10,1.61,2.700000e+00,2.70,1.66,1.66,...,2.000000e+00,2.00,1.280000e+00,1.500000e+00,3.000000e+00,2.450000e+00,2.700000e+00,5.500000e+00,1.900000e+00,1.500000e+00
BWA,1.450000e+00,4.40,4.900000e+00,1.350000e+00,3.30,4.75,2.500000e+00,2.40,4.70,5.00,...,3.700000e+00,4.10,9.000000e+00,6.750000e+00,2.400000e+00,3.000000e+00,2.800000e+00,1.750000e+00,4.600000e+00,6.250000e+00
BWD,3.700000e+00,3.30,3.400000e+00,4.250000e+00,3.10,3.50,3.100000e+00,3.15,3.50,3.35,...,3.600000e+00,3.50,5.750000e+00,4.000000e+00,3.300000e+00,3.200000e+00,3.000000e+00,3.600000e+00,3.500000e+00,4.600000e+00
BWH,7.000000e+00,1.75,1.650000e+00,8.000000e+00,2.10,1.65,2.650000e+00,2.70,1.65,1.65,...,2.000000e+00,1.91,1.300000e+00,1.530000e+00,3.000000e+00,2.450000e+00,2.750000e+00,5.000000e+00,1.830000e+00,1.480000e+00
IWA,1.500000e+00,3.60,4.400000e+00,1.500000e+00,3.20,4.40,2.700000e+00,2.50,4.80,4.00,...,3.600000e+00,3.95,8.500000e+00,6.900000e+00,2.450000e+00,3.100000e+00,2.850000e+00,1.700000e+00,4.500000e+00,6.100000e+00
IWD,3.500000e+00,3.00,3.100000e+00,3.500000e+00,2.90,3.10,3.000000e+00,3.00,3.30,3.20,...,3.550000e+00,3.40,6.000000e+00,3.950000e+00,3.250000e+00,3.100000e+00,3.050000e+00,3.500000e+00,3.300000e+00,4.500000e+00
IWH,5.400000e+00,1.90,1.700000e+00,5.400000e+00,2.10,1.70,2.300000e+00,2.50,1.60,1.75,...,2.000000e+00,1.97,1.300000e+00,1.530000e+00,2.950000e+00,2.450000e+00,2.700000e+00,5.600000e+00,1.900000e+00,1.500000e+00
VCA,1.450000e+00,3.75,4.500000e+00,1.450000e+00,3.25,5.00,2.500000e+00,2.25,5.00,4.60,...,3.600000e+00,3.90,9.500000e+00,7.000000e+00,2.450000e+00,3.000000e+00,2.800000e+00,1.730000e+00,4.600000e+00,5.750000e+00
VCD,3.750000e+00,3.25,3.400000e+00,3.600000e+00,3.20,3.30,3.100000e+00,3.00,3.30,3.30,...,3.600000e+00,3.50,5.750000e+00,4.100000e+00,3.300000e+00,3.130000e+00,3.000000e+00,3.500000e+00,3.300000e+00,4.500000e+00
VCH,6.500000e+00,1.85,1.650000e+00,6.500000e+00,2.00,1.60,2.500000e+00,2.90,1.60,1.65,...,2.000000e+00,1.95,1.290000e+00,1.500000e+00,2.900000e+00,2.450000e+00,2.700000e+00,5.200000e+00,1.850000e+00,1.500000e+00
WHA,1.500000e+00,3.50,4.500000e+00,1.440000e+00,3.00,4.50,2.620000e+00,2.25,5.50,5.00,...,3.700000e+00,4.00,1.000000e+01,7.000000e+00,2.450000e+00,3.000000e+00,2.880000e+00,1.730000e+00,4.500000e+00,6.500000e+00
WHD,3.400000e+00,3.10,3.200000e+00,3.600000e+00,3.10,3.30,3.100000e+00,3.20,3.30,3.30,...,3.600000e+00,3.40,5.800000e+00,4.200000e+00,3.300000e+00,3.100000e+00,3.000000e+00,3.500000e+00,3.400000e+00,4.330000e+00
WHH,6.000000e+00,1.95,1.700000e+00,6.500000e+00,2.15,1.66,2.370000e+00,2.75,1.57,1.61,...,2.000000e+00,2.00,1.290000e+00,1.500000e+00,3.000000e+00,2.550000e+00,2.700000e+00,5.500000e+00,1.880000e+00,1.500000e+00
FTR,1.000000e+00,2.00,1.000000e+00,0.000000e+00,2.00,0.00,0.000000e+00,2.00,2.00,2.00,...,1.000000e+00,0.00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,1.000000e+00,0.000000e+00,2.000000e+00

In [30]:
y = df.FTR # define the target variable (dependent variable) as y
df = df.drop(['FTR'],axis=1)

In [31]:
# create training and testing vars
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2)

In [32]:
print (X_train.shape)
print (y_train.shape)
print (X_test.shape)
print (y_test.shape)

(4231, 19)
(4231,)
(1058, 19)
(1058,)

In [33]:
X_train.to_csv(r'X_train.csv')
y_train.to_csv(r'y_train.csv')
X_test.to_csv(r'X_test.csv')
y_test.to_csv(r'y_test.csv')

/home/jacoboj/miniconda3/envs/genml/lib/python3.7/site-packages/ipykernel_launcher.py:2: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

/home/jacoboj/miniconda3/envs/genml/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  after removing the cwd from sys.path.

In [34]:
columnas_xtrain = X_train.columns.tolist()
columnas_xtrain

['AwayTeam',
 'AwayValue',
 'HomeTeam',
 'HomeValue',
 'B365A',
 'B365D',
 'B365H',
 'BWA',
 'BWD',
 'BWH',
 'IWA',
 'IWD',
 'IWH',
 'VCA',
 'VCD',
 'VCH',
 'WHA',
 'WHD',
 'WHH']

## MODELS

In [35]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification
from sklearn.ensemble import GradientBoostingClassifier
from sklearn import preprocessing
import numpy as np
from scipy.stats import f
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import GridSearchCV
from sklearn import ensemble
from sklearn import metrics

In [ ]:
#clf_v1 = ''''''GradientBoostingClassifier'''''' (loss='deviance', 
#learning_rate=0.1, n_estimators=100, subsample=1.0, 
#criterion='friedman_mse', min_samples_split=2, 
#min_samples_leaf=1, min_weight_fraction_leaf=0.0, 
#max_depth=3, min_impurity_decrease=0.0, min_impurity_split=None, 
#init=None, random_state=None, max_features=None, verbose=0, 
#max_leaf_nodes=None, warm_start=False, n_iter_no_change=None, tol=0.0001)
###############ACCURACY: 0.53

#'''''''''''''RandomForestClassifier'''''''''''''(bootstrap=True, class_weight=None,
#                                              criterion='gini', max_depth=None,
#                                              max_features='auto',
#                                             max_leaf_nodes=None,
#                                            min_impurity_decrease=0.0,
#                                           min_impurity_split=None,
#                                          min_samples_leaf=1,
#                                         min_samples_split=2,
#                                        min_weight_fraction_leaf=0.0,
#                                       n_estimators='warn', n_jobs=None,
#                                      oob_score=False, random_state=14,
#                                     verbose=0, warm_start=False),
#   iid='warn', n_jobs=None,
#  param_grid={'criterion': ['gini', 'entropy'],
#             'max_features': [2, 10, 'auto'],
#            'min_samples_leaf': [2, 4, 6], 'n_estimators': [100]},
# pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
# scoring=None, verbose=0)
###############ACCURACY: 0.51

In [39]:
parameter_space = {
"max_features": [2, 10, 'auto'],
"n_estimators": [100,],
"criterion": ["gini", "entropy"],
"min_samples_leaf": [2, 4, 6],
}

clf = GridSearchCV(RandomForestClassifier(random_state=14), parameter_space)
#clf_v2 = GridSearchCV(GradientBoostingClassifier(), parameters, cv=10, n_jobs=-1)

In [40]:
#Train the model using the training sets y_pred=clf.predict(X_test)
#clf_v1.fit(X_train,y_train) #Accuracy: 0.52
clf.fit(X_train,y_train) #

/home/jacoboj/miniconda3/envs/genml/lib/python3.7/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False, random_state=14,
                                              verbose=0, warm_start=False),
             iid='warn', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_features': [2, 10, 'auto'],
                         'min_samples_leaf': [2, 4, 6], 'n_estimators': [100]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [42]:
y_pred=clf.predict(X_test)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

Accuracy: 0.5198487712665406

In [ ]:
'''def grid_model(modelo, params, X_train, y_train, X_test, cv = 5):
    grid = GridSearchCV(modelo, params, cv=cv)
    grid.fit(X_train, y_train)
    best_m = grid.best_estimator_.fit(X_train, y_train)
    y_pred = best_m.predict(X_test)
    return y_pred, best_m

modelo = ensemble.GradientBoostingRegressor()

params = {'n_estimators' : [450, 750, 1000, 1200], 'max_depth' : [3,4,5,6], 
          'min_samples_split' : [5,7,8,9], 'learning_rate' : [0.1]}

y_pred = grid_model(modelo, params, X_train, y_train, X_test, cv = 5)'''

In [ ]:
to_predict = pd.read_csv('//home/jacoboj/Escritorio/data_football/prueba19.csv')

In [ ]:
new_df = to_predict[['AwayTeam', 'HomeTeam', 'B365A', 'B365D', 'B365H', 'BWA',
                  'BWD', 'BWH','IWA', 'IWD', 'IWH', 'VCA', 'VCD', 'VCH', 'WHA', 'WHD', 'WHH', 'HTR', 'FTR']]

In [ ]:
new_df.head()

In [ ]:
HomeValue = pd.Series([]) # Create Serie to add market value team

#Market Value Teams 2018
for i in range(len(new_df)):
    if new_df['HomeTeam'][i] == 'Granada':
        HomeValue[i] = 33500000
    elif new_df['HomeTeam'][i] == 'Ath Bilbao':
        HomeValue[i] = 224000000
    elif new_df['HomeTeam'][i] == 'Valencia':
        HomeValue[i] = 495500000
    elif new_df['HomeTeam'][i] == 'Ath Madrid':
        HomeValue[i] = 872500000
    elif new_df['HomeTeam'][i] == 'Eibar':
        HomeValue[i] = 69600000
    elif new_df['HomeTeam'][i] == 'Sociedad':
        HomeValue[i] = 309800000
    elif new_df['HomeTeam'][i] == 'Espanol':
        HomeValue[i] = 150300000
    elif new_df['HomeTeam'][i] == 'Villarreal':
        HomeValue[i] = 211700000
    elif new_df['HomeTeam'][i] == 'Valladolid':
        HomeValue[i] = 91300000
    elif new_df['HomeTeam'][i] == 'Sevilla':
        HomeValue[i] = 28300000
    elif new_df['HomeTeam'][i] == 'Alaves':
        HomeValue[i] = 90200000
    elif new_df['HomeTeam'][i] == 'Mallorca':
        HomeValue[i] = 58550000
    elif new_df['HomeTeam'][i] == 'Real Madrid':
        HomeValue[i] = 1190000000
    elif new_df['HomeTeam'][i] == 'Barcelona':
        HomeValue[i] = 1180000000
    elif new_df['HomeTeam'][i] == 'Leganes':
        HomeValue[i] = 106800000
    elif new_df['HomeTeam'][i] == 'Betis':
        HomeValue[i] = 292500000
    elif new_df['HomeTeam'][i] == 'Getafe':
        HomeValue[i] = 151200000
    elif new_df['HomeTeam'][i] == 'Osasuna':
        HomeValue[i] = 43500000
    elif new_df['HomeTeam'][i] == 'Celta':
        HomeValue[i] = 226300000
    elif new_df['HomeTeam'][i] == 'Levante':
        HomeValue[i] = 102400000

new_df.insert(2, "HomeValue", HomeValue) # Execute

In [ ]:
new_df.head()

In [ ]:
AwayValue = pd.Series([]) # Create Serie to add market value team

#Market Value Teams 2019
for i in range(len(new_df)):
    if new_df['AwayTeam'][i] == 'Granada':
        AwayValue[i] = 33500000
    elif new_df['AwayTeam'][i] == 'Ath Bilbao':
        AwayValue[i] = 224000000
    elif new_df['AwayTeam'][i] == 'Valencia':
        AwayValue[i] = 495500000
    elif new_df['AwayTeam'][i] == 'Ath Madrid':
        AwayValue[i] = 872500000
    elif new_df['AwayTeam'][i] == 'Eibar':
        AwayValue[i] = 69600000
    elif new_df['AwayTeam'][i] == 'Sociedad':
        AwayValue[i] = 309800000
    elif new_df['AwayTeam'][i] == 'Espanol':
        AwayValue[i] = 150300000
    elif new_df['AwayTeam'][i] == 'Villarreal':
        AwayValue[i] = 211700000
    elif new_df['AwayTeam'][i] == 'Valladolid':
        AwayValue[i] = 91300000
    elif new_df['AwayTeam'][i] == 'Sevilla':
        AwayValue[i] = 28300000
    elif new_df['AwayTeam'][i] == 'Alaves':
        AwayValue[i] = 90200000
    elif new_df['AwayTeam'][i] == 'Mallorca':
        AwayValue[i] = 58550000
    elif new_df['AwayTeam'][i] == 'Real Madrid':
        AwayValue[i] = 1190000000
    elif new_df['AwayTeam'][i] == 'Barcelona':
        AwayValue[i] = 1180000000
    elif new_df['AwayTeam'][i] == 'Leganes':
        AwayValue[i] = 106800000
    elif new_df['AwayTeam'][i] == 'Betis':
        AwayValue[i] = 292500000
    elif new_df['AwayTeam'][i] == 'Getafe':
        AwayValue[i] = 151200000
    elif new_df['AwayTeam'][i] == 'Osasuna':
        AwayValue[i] = 43500000
    elif new_df['AwayTeam'][i] == 'Celta':
        AwayValue[i] = 226300000
    elif new_df['AwayTeam'][i] == 'Levante':
        AwayValue[i] = 102400000

new_df.insert(4, "AwayValue", AwayValue) # Execute

In [ ]:
new_df.head()

In [ ]:
new_df = new_df[['AwayTeam', 'AwayValue', 'HomeTeam', 'HomeValue', 'B365A', 'B365D', 'B365H', 'BWA',
                  'BWD', 'BWH','IWA', 'IWD', 'IWH', 'VCA', 'VCD', 'VCH', 'WHA', 'WHD', 'WHH', 'HTR', 'FTR']]

In [ ]:
new_df = new_df[['AwayTeam','AwayValue', 'HomeTeam', 'HomeValue', 'B365A', 'B365D', 'B365H', 'BWA', 'BWD', 'BWH', 'IWA', 'IWD',
 'IWH', 'VCA', 'VCD', 'VCH', 'WHA', 'WHD', 'WHH', 'HTR', 'FTR']]

In [ ]:
new_df.head()

In [ ]:
to_encode_pred = new_df.select_dtypes(include=[object])
to_encode_pred.head()
new_df.drop(['AwayTeam', 'HomeTeam', 'HTR', 'FTR'], axis=1, inplace=True)

In [ ]:
# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()


# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
features_encoded_pred = to_encode_pred.apply(le.fit_transform)
features_encoded_pred.head(10)

In [ ]:
result_pred = pd.concat([new_df.stack(), features_encoded_pred.stack()], axis=0).unstack()

In [ ]:
result_pred.head()

In [ ]:
result_pred = result_pred[['AwayTeam','AwayValue', 'HomeTeam', 'HomeValue', 'B365A', 'B365D', 'B365H', 'BWA', 'BWD', 'BWH', 'IWA', 'IWD',
 'IWH', 'VCA', 'VCD', 'VCH', 'WHA', 'WHD', 'WHH', 'HTR', 'FTR']]

In [ ]:
result_pred.head()

In [ ]:
asd = result_pred.FTR

In [ ]:
result_pred.drop(['FTR'], axis=1, inplace=True)

In [ ]:
result_pred.head()

In [ ]:
y_pred_2=clf2.predict(result_pred)

In [ ]:
print("Accuracy:",metrics.accuracy_score(asd, y_pred_2))